version: '3.8'

services:
  mywebsite:
    image: ghcr.io/ferilee/mywebsite:latest
    ports:
      - "4128:4128"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
