version: '3.8'

services:
  app:
    image: ghcr.io/ferilee/mywebsite:latest
    ports:
      - "4128:4128"
    volumes:
      - ./sqlite.db:/app/sqlite.db
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
